homepage:
    pattern: '/:slug'
    route: {controller: 'Default', action: 'indexAction'}
    method: 'GET'
page_show:
    pattern: '/hello/world'
    route: {controller: 'Default', action: 'showAction'}
